version: "3.9"
   
services:
  db:
    image: postgres:13.3
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "20210258"
      POSTGRES_DB: user_login_system
    ports:
      - "5434:5432"
  api:
    build: .
    restart: always
    volumes:
      - .:/app  
    ports:
      - "3141:3141"
    depends_on:
      - db
    environment: 
      PORT: 3141
      DB_HOST: db
volumes:
  db_data: {}
